"""feat: initial bridge schema

Revision ID: d755d3af7afc
Revises: 
Create Date: 2026-03-27 06:01:00.988488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd755d3af7afc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('cross_chain_swaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onchain_id', sa.String(), nullable=True),
    sa.Column('stellar_htlc_id', sa.String(), nullable=True),
    sa.Column('other_chain', sa.String(), nullable=False),
    sa.Column('other_chain_tx', sa.String(), nullable=True),
    sa.Column('stellar_party', sa.String(), nullable=False),
    sa.Column('other_party', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_chain_swaps_created_at'), 'cross_chain_swaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_cross_chain_swaps_onchain_id'), 'cross_chain_swaps', ['onchain_id'], unique=True)
    op.create_table('htlcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onchain_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('receiver', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('hash_lock', sa.String(), nullable=False),
    sa.Column('time_lock', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('hash_algorithm', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_htlcs_created_at'), 'htlcs', ['created_at'], unique=False)
    op.create_index(op.f('ix_htlcs_onchain_id'), 'htlcs', ['onchain_id'], unique=True)
    op.create_index(op.f('ix_htlcs_receiver'), 'htlcs', ['receiver'], unique=False)
    op.create_index(op.f('ix_htlcs_sender'), 'htlcs', ['sender'], unique=False)
    op.create_table('swap_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('source_chain', sa.String(), nullable=False),
    sa.Column('target_chain', sa.String(), nullable=False),
    sa.Column('source_asset', sa.String(), nullable=False),
    sa.Column('target_asset', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_orders_created_at'), 'swap_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_swap_orders_user_address'), 'swap_orders', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_orders_user_address'), table_name='swap_orders')
    op.drop_index(op.f('ix_swap_orders_created_at'), table_name='swap_orders')
    op.drop_table('swap_orders')
    op.drop_index(op.f('ix_htlcs_sender'), table_name='htlcs')
    op.drop_index(op.f('ix_htlcs_receiver'), table_name='htlcs')
    op.drop_index(op.f('ix_htlcs_onchain_id'), table_name='htlcs')
    op.drop_index(op.f('ix_htlcs_created_at'), table_name='htlcs')
    op.drop_table('htlcs')
    op.drop_index(op.f('ix_cross_chain_swaps_onchain_id'), table_name='cross_chain_swaps')
    op.drop_index(op.f('ix_cross_chain_swaps_created_at'), table_name='cross_chain_swaps')
    op.drop_table('cross_chain_swaps')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
